### ISSUE TITLE
failed to push

### ISSUE THREAD

**Issue by zyuying** [PCMDI/PMPObs-cmor-tables#13]
@durack1 @gleckler1  I tried to 'git push' my new modifications, but it shows 
"fatal: unable to access 'https://github.com/PCMDI/PMPObs-cmor-tables/': SSL connect error "
Before that, I 'git add' several new codes and 'git commit -am "...."' 
Is there anything wrong?

**Comment by lee1043** [comment]
@durack1 @zyuying the crunchy issue was solved, works for me.

**Comment by durack1** [comment]
Thanks @lee1043, I had assumed we're all fixed here, @zyuying can confirm this week

**Comment by zyuying** [comment]
@durack1 @lee1043 @gleckler1 I've 'git push' my changes successfully. Thanks.
