### ISSUE TITLE
Q:  should we be starting with /orig or previously processed (e.g., /atm/mo/rlut/CERES)

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PMPObs-cmor-tables#14]
@durack1 @zyuying   The tests YZ has set things up so far use as inputs data that was already processed (with CMOR2).   That makes things easier, so maybe we should just move forward.  On the other hand,  the next time these datasets get updated (with newer versions or extended timeseries) we will likely have to rewrite these codes rather than just rerun.   

Its not too late to start focusing on /orig .... any thoughts?

**Comment by durack1** [comment]
@gleckler1 my opinion is we do this right, so start from the original downloaded files and then we can update these files as they become available

**Comment by zyuying** [comment]
@gleckler1 @durack1 I agree that we start from the original files. I will work on the current codes and convert them to a new version.
