### ISSUE TITLE
Q regarding datasets to be updated

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PMPObs-cmor-tables#3]
Looks like there are two lists in writeJson.py of datasets to be updated, starting on lines 110 and 202.
Maybe this is WIP?   Otherwise I don’t see how they could be comments without line beginning with “#”

**Comment by durack1** [comment]
https://github.com/PCMDI/PMPObs-cmor-tables/blob/master/src/writeJson.py#L109-L134 and https://github.com/PCMDI/PMPObs-cmor-tables/blob/master/src/writeJson.py#L201-L232 are block comments, so are ignored by the python interpreter.
```
'''
comment
comment
'''
```
Works as a block (multi-line) comment in python

Will close this, as it's a non-issue
