### ISSUE TITLE
comment... need to know....

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PMPObs-cmor-tables#4]
@durack1  While it would be useful for Yuying, Peter and Jiwoo to understand big picture of what and how writejson.py does, I think only a very small block of code needs to be changed by any of us.  It will be good for Yuying to know this so she does not attempt understanding every line of code.

**Comment by durack1** [comment]
@gleckler1 let's chat about this specifically today at 3:30, @lee1043 did you also want to join?

Will close

**Comment by gleckler1** [comment]
@lee1043 @durack1  JW may have enough going on with his day but I'll talk to him about it.

**Comment by lee1043** [comment]
@durack1 @gleckler1 Thanks for tagging me. Wish I could join but I have some work that needs to be done by next morning. I will talk to @gleckler1 later.
