### ISSUE TITLE
change name of ERA script in test

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PMPObs-cmor-tables#8]
@zyuying @durack1   Excellent!! 👍   Maybe we should change the name of the script from  	runCmorDemo_3dtest.py to something like  ERA-INT_3dtest.py ?

**Comment by zyuying** [comment]
There is a new file named runCmor_ERAINT_3D.py, but it seems the file hasn't been added to the master. I will do it again.

**Comment by gleckler1** [comment]
@zyuying  maybe you need to do a "git add" first...
git add filename
git commit -am "just added file"
git push

or something like that ;-)

**Comment by zyuying** [comment]
@gleckler1 @durack1  Can you see the new code named runCmor_ERAINT_3D.py in ./test now? I "git push" it, but I'm not sure if I've merged it to the master.

**Comment by gleckler1** [comment]
@zyuying  Yes its there!   So I'll now "close this issue" 
Thanks!
